### ISSUE TITLE
How do you tag metrics?

### ISSUE THREAD

**Issue by grayaii** [DataDog/uwsgi-dogstatsd#14]
I need to differentiate metrics coming from different environments.

I see some work for tags in the plugin.c file, but I'm not sure how to use it?

Is there an example on using tags?

**Comment by Tenzer** [comment]
See #13 and #15. They add an option of setting custom tags to be added to the metrics. Unfortunately they haven't been merged in yet.

**Comment by remeh** [comment]
Hello @grayaii 
The custom tags support has been merged into master. It's documented in the README and the configuration field to use is named `dogstatsd-extra-tags`. I'm closing your issue.
