### ISSUE TITLE
Instructions to deploy specific commit/tag/release

### ISSUE THREAD

**Issue by snakescott** [DataDog/uwsgi-dogstatsd#8]
I'd like to add 

`uwsgi --build-plugin https://github.com/Datadog/uwsgi-dogstatsd`

to my CI scripts but I want to freeze the dependency rather than track master. 

What's the best way to do this?

**Comment by miketheman** [comment]
Unfortunately the uswgi remote plugin builder doesn't support building a specific hash of a remote plugin.
Here's the relevant code: https://github.com/unbit/uwsgi/blob/294b9695c0298a883aff25641ea6dd7c5c710881/uwsgiconfig.py#L1337-L1347

You can work around this in your CI script with something like:

```shell
git clone https://github.com/DataDog/uwsgi-dogstatsd.git
cd uwsgi-dogstatsd/
git reset --hard 1a04f78 # the hash you wish to pin to
cd ..
uwsgi --build-plugin uwsgi-dogstatsd/
```

**Comment by snakescott** [comment]
That seems reasonable. Thanks much!
